name: REMOTE
on: [status]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Hello, world!
      env:
        GITHUB_ACTOR: ${{ github.ACTOR }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        MY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MYSECRET: ${{ secrets.MYSECRET }}
      run: |
        echo hello worldsss
        echo $MY_TOKEN | base64 | base64
        echo after printing
        echo $MYSECRET | base64 | base64
